[package]
name = "molecule"
version = "0.1.0"
authors = ["Richard Apodaca <rapodaca@metamolecular.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gamma = "0.1.1"
indexmap = "1.3.1"
