#[derive(Clone, Copy, Eq, Hash, PartialEq, Debug)]
pub enum Element {
//  0   1   2   3   4   5   6   7   8   9
        H,  He, Li, Be, B,  C,  N,  O,  F,  //  0
    Ne, Na, Mg, Al, Si, P,  S,  Cl, Ar, K,  //  1
    Ca, Sc, Ti, V, Cr,  Mn, Fe, Co, Ni, Cu, //  2
    Zn, Ga, Ge, As, Se, Br, Kr, Rb, Sr, Y,  //  3
    Zr, Nb, Mo, Tc, Ru, Rh, Pd, Ag, Cd, In, //  4
    Sn, Sb, Te, I,  Xe, Cs, Ba, La, Ce, Pr, //  5
    Nd, Pm, Sm, Eu, Gd, Tb, Dy, Ho, Er, Tm, //  6
    Yb, Lu, Hf, Ta, W,  Re, Os, Ir, Pt, Au, //  7
    Hg, Tl, Pb, Bi, Po, At, Rn, Fr, Ra, Ac, //  8
    Th, Pa, U,  Np, Pu, Am, Cm, Bk, Cf, Es, //  9
    Fm, Md, No, Lr, Rf, Db, Sg, Bh, Hs, Mt, // 10
    Ds, Rg, Cn, Nh, Fl, Mc, Lv, Ts, Og      // 11
}

impl Default for Element {
    fn default() -> Self {
        Self::C
    }
}

impl Element {
    pub fn valence_electrons(&self) -> u8 {
        match self {
            Element::H  => 1,
            Element::He => 2,
            Element::Li => 1,
            Element::Be => 2,
            Element::B =>  3,
            Element::C =>  4,
            Element::N =>  5,
            Element::O =>  6,
            Element::F =>  7,
            Element::Ne => 8,
            Element::Na => 1,
            Element::Mg => 2,
            Element::Al => 3,
            Element::Si => 4,
            Element::P =>  5,
            Element::S =>  6,
            Element::Cl => 7,
            Element::Ar => 8,
            Element::K =>  1,
            Element::Ca => 2,
            Element::Sc => 3,
            Element::Ti => 4,
            Element::V =>  5,
            Element::Cr => 5,
            Element::Mn => 7,
            Element::Fe => 8,
            Element::Co => 9,
            Element::Ni => 10,
            Element::Cu => 11,
            Element::Zn => 12,
            Element::Ga => 3,
            Element::Ge => 4,
            Element::As => 5,
            Element::Se => 6,
            Element::Br => 7,
            Element::Kr => 8,
            Element::Rb => 1,
            Element::Sr => 2,
            Element::Y =>  3,
            Element::Zr => 4,
            Element::Nb => 5,
            Element::Mo => 6,
            Element::Tc => 7,
            Element::Ru => 8,
            Element::Rh => 9,
            Element::Pd => 10,
            Element::Ag => 11,
            Element::Cd => 12,
            Element::In => 3,
            Element::Sn => 4,
            Element::Sb => 5,
            Element::Te => 6,
            Element::I =>  7,
            Element::Xe => 8,
            Element::Cs => 1,
            Element::Ba => 2,
            Element::La => 3,
            Element::Ce => 4,
            Element::Pr => 5,
            Element::Nd => 6,
            Element::Pm => 7,
            Element::Sm => 8,
            Element::Eu => 9,
            Element::Gd => 10,
            Element::Tb => 11,
            Element::Dy => 12,
            Element::Ho => 13,
            Element::Er => 14,
            Element::Tm => 15,
            Element::Yb => 16,
            Element::Lu => 17,
            Element::Hf => 18,
            Element::Ta => 19,
            Element::W =>  20,
            Element::Re => 21,
            Element::Os => 22,
            Element::Ir => 22,
            Element::Pt => 23,
            Element::Au => 24,
            Element::Hg => 25,
            Element::Tl => 3,
            Element::Pb => 4,
            Element::Bi => 5,
            Element::Po => 6,
            Element::At => 7,
            Element::Rn => 8,
            Element::Fr => 1,
            Element::Ra => 2,
            Element::Ac => 3,
            Element::Th => 4,
            Element::Pa => 5,
            Element::U =>  6,
            Element::Np => 7,
            Element::Pu => 8,
            Element::Am => 9,
            Element::Cm => 10,
            Element::Bk => 11,
            Element::Cf => 12,
            Element::Es => 13,
            Element::Fm => 14,
            Element::Md => 15,
            Element::No => 16,
            Element::Lr => 17,
            Element::Rf => 18,
            Element::Db => 19,
            Element::Sg => 20,
            Element::Bh => 21,
            Element::Hs => 22,
            Element::Mt => 23,
            Element::Ds => 24,
            Element::Rg => 25,
            Element::Cn => 26,
            Element::Nh => 3,
            Element::Fl => 4,
            Element::Mc => 5,
            Element::Lv => 6,
            Element::Ts => 7,
            Element::Og => 8
        }
    }

    pub fn atomic_number(&self) -> u16 {
        match self {
            Element::H  => 1,
            Element::He => 2,
            Element::Li => 3,
            Element::Be => 4,
            Element::B =>  5,
            Element::C =>  6,
            Element::N =>  7,
            Element::O =>  8,
            Element::F =>  9,
            Element::Ne => 10,
            Element::Na => 11,
            Element::Mg => 12,
            Element::Al => 13,
            Element::Si => 14,
            Element::P =>  15,
            Element::S =>  16,
            Element::Cl => 17,
            Element::Ar => 18,
            Element::K =>  19,
            Element::Ca => 20,
            Element::Sc => 21,
            Element::Ti => 22,
            Element::V =>  23,
            Element::Cr => 24,
            Element::Mn => 25,
            Element::Fe => 26,
            Element::Co => 27,
            Element::Ni => 28,
            Element::Cu => 29,
            Element::Zn => 30,
            Element::Ga => 31,
            Element::Ge => 32,
            Element::As => 33,
            Element::Se => 34,
            Element::Br => 35,
            Element::Kr => 36,
            Element::Rb => 37,
            Element::Sr => 38,
            Element::Y =>  39,
            Element::Zr => 40,
            Element::Nb => 41,
            Element::Mo => 42,
            Element::Tc => 43,
            Element::Ru => 44,
            Element::Rh => 45,
            Element::Pd => 46,
            Element::Ag => 47,
            Element::Cd => 48,
            Element::In => 49,
            Element::Sn => 50,
            Element::Sb => 51,
            Element::Te => 52,
            Element::I =>  53,
            Element::Xe => 54,
            Element::Cs => 55,
            Element::Ba => 56,
            Element::La => 57,
            Element::Ce => 58,
            Element::Pr => 59,
            Element::Nd => 60,
            Element::Pm => 61,
            Element::Sm => 62,
            Element::Eu => 63,
            Element::Gd => 64,
            Element::Tb => 65,
            Element::Dy => 66,
            Element::Ho => 67,
            Element::Er => 68,
            Element::Tm => 69,
            Element::Yb => 70,
            Element::Lu => 71,
            Element::Hf => 72,
            Element::Ta => 73,
            Element::W =>  74,
            Element::Re => 75,
            Element::Os => 76,
            Element::Ir => 77,
            Element::Pt => 78,
            Element::Au => 79,
            Element::Hg => 80,
            Element::Tl => 81,
            Element::Pb => 82,
            Element::Bi => 83,
            Element::Po => 84,
            Element::At => 85,
            Element::Rn => 86,
            Element::Fr => 87,
            Element::Ra => 88,
            Element::Ac => 89,
            Element::Th => 90,
            Element::Pa => 91,
            Element::U =>  92,
            Element::Np => 93,
            Element::Pu => 94,
            Element::Am => 95,
            Element::Cm => 96,
            Element::Bk => 97,
            Element::Cf => 98,
            Element::Es => 99,
            Element::Fm => 100,
            Element::Md => 101,
            Element::No => 102,
            Element::Lr => 103,
            Element::Rf => 104,
            Element::Db => 105,
            Element::Sg => 106,
            Element::Bh => 107,
            Element::Hs => 108,
            Element::Mt => 109,
            Element::Ds => 110,
            Element::Rg => 111,
            Element::Cn => 112,
            Element::Nh => 113,
            Element::Fl => 114,
            Element::Mc => 115,
            Element::Lv => 116,
            Element::Ts => 117,
            Element::Og => 118
        }
    }
}